import { GoogleGenAI } from "@google/genai";
import { Sticky, ChatMessage } from "../types";

const getAIClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    console.warn("API Key not found in environment variables");
    return null;
  }
  return new GoogleGenAI({ apiKey });
};

export const generateIcebreaker = async (): Promise<string> => {
  const ai = getAIClient();
  if (!ai) return "What's the most unusual food you've ever eaten?";

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: "Generate a single, fun, short, and unique icebreaker question for a remote team workshop. Just the question.",
    });
    return response.text?.trim() || "If you could have any superpower, what would it be?";
  } catch (error) {
    console.error("Failed to generate icebreaker", error);
    return "What is your favorite movie of all time?";
  }
};

export const generateMagicReport = async (
  boardName: string,
  stickies: Sticky[],
  messages: ChatMessage[]
): Promise<string> => {
  const ai = getAIClient();
  if (!ai) return "API Key missing. Cannot generate report.";

  const stickiesText = stickies.map(s => `- [Votes: ${s.votes}] ${s.content} (Color: ${s.color})`).join('\n');
  const chatText = messages.map(m => `- ${m.content}`).join('\n');

  const prompt = `
    You are an expert project manager and workshop facilitator. 
    Create a "Magic Project Report" for a session titled "${boardName}".
    
    Data Source:
    
    STICKY NOTES (Ideas/Tasks):
    ${stickiesText}
    
    SCRIBBLE WALL (Discussion):
    ${chatText}
    
    Output Format (Use Markdown):
    # 🪄 Magic Report: ${boardName}
    
    ## 🏆 Top Ideas (Based on votes & sentiment)
    [List top 3 ideas]
    
    ## 📝 Executive Summary
    [A 2-3 sentence summary of the session]
    
    ## 🚀 Action Items
    [Infer 3-5 action items based on the notes]
    
    ## 💡 Key Discussion Points
    [Summarize the chat themes]
    
    ---
    *Generated by JamBoard AI*
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    return response.text || "Failed to generate report text.";
  } catch (error) {
    console.error("Failed to generate report", error);
    return "Error generating report. Please check your API configuration.";
  }
};